#ifndef CREST_SYSCALL_H
#define CREST_SYSCALL_H

typedef enum {
    SYSCALL_DELAY = 0,
    SYSCALL_QUEUE_SEND,
    SYSCALL_QUEUE_RECV,
    SYSCALL_SEM_POST,
    SYSCALL_SEM_WAIT,
    SYSCALL_MUTEX_LOCK,
    SYSCALL_MUTEX_UNLOCK,
    SYSCALL_UART_WRITE,
    SYSCALL_MAX
} syscall_id_t;

#endif /* CREST_SYSCALL_H */